version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
      - image: postgres:9.5
        environment:
        - POSTGRES_DB: grapeql-test
        - POSTGRES_USER: ubuntu
        - POSTGRES_PASSWORD: ubuntu
    
    working_directory: ~/grapeql

    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      
      - run: node ./scripts/init.js

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm run test
